### ISSUE TITLE
Module resolution fails

### ISSUE THREAD

**Issue by EtherTyper** [chmontgomery/gulp-shrinkwrap#12]
Dependency resolution fails for `graceful-fs@3.0.6`, which is a dependency of `gulp-shrinkwrap@2.0.1`.

Here is the error:

``` js
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/Users/ethertyper/WebstormProjects/WestlakeAPC.github.io/node_modules/gulp-shrinkwrap/node_modules/npm/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

And here is the dependency tree:

```
├─┬ gulp-shrinkwrap@2.0.1
│ ├── graceful-fs@3.0.6 
│ └─┬ npm@2.7.0
│   └── graceful-fs@3.0.5 
```

**Comment by chmontgomery** [comment]
fixed in `v2.0.2`. Please try it out and let me know if it works
